### ISSUE TITLE
Installation does not work in R3.5.1

### ISSUE THREAD

**Issue by markushaun** [mkearney/viewtweets#1]
![image](https://user-images.githubusercontent.com/35169830/46694396-fe203e80-cc0c-11e8-8c99-d5e65bdadeec.png)

**Comment by mkearney** [comment]
The [tfse](https://github.com/mkearney/tfse) package is pending on CRAN. Until it gets approved, you can install from Github

``` r
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mkearney/tfse")
```
